language: python

dist: trusty

services: 
  - docker

branches:
  only:
   - master
   - develop

before_script:
  - chmod +x travis/configure.sh
  - travis/configure.sh

script:
  - chmod +x travis/build.sh
  - travis/build.sh

deploy:
  provider: script
  script: bash travis/deploy.sh
